### ISSUE TITLE
SomNode(X,20)

### ISSUE THREAD

**Issue by rocketeer1998** [WhirlFirst/somde#4]
Hi @WhirlFirst , thanks for your contribution to SOMDE! I want to know more details about your documentation. What does 20 mean in 

```
from somde import SomNode
som = SomNode(X,20)
```

Empirically, the number of SOM spots is reversely proportional to this value. But I don't know why.   

I'm looking forward to your reply!

**Comment by WhirlFirst** [comment]
Hi,
20 is the neighbor number, as defined in the manuscript:
![image](https://github.com/WhirlFirst/somde/assets/23123386/3b9c3d21-6673-4e79-8590-88deba0b6aba)

**Comment by rocketeer1998** [comment]
Clear explanation!
